cc_library(
    name = "people",
    srcs = ["people.cc"],
    hdrs = ["people.h"],
)

cc_test(
    name = "people_test",
    srcs = ["people_test.cc"],
    deps = [
        ":people",
        "@catch2//:catch2_main",
    ],
)
